/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package maua.poo.br.pi;

import java.util.Locale;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 25.01392-1
 */
public class TelaRemoverQuestão extends javax.swing.JFrame {
    static {
        Locale.setDefault(new Locale("pt", "BR"));
    }

    /**
     * Creates new form TelaRemoverQuestão
     */
    public TelaRemoverQuestão() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dificuldadeCombo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        dificuldadeCombo1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        removerPanel = new javax.swing.JPanel();
        materiaCombo = new javax.swing.JComboBox<>();
        materiaLabel = new javax.swing.JLabel();
        serieCombo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        dificuldadeCombo2 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        questoesTable = new javax.swing.JTable();
        voltarRemoverButton = new javax.swing.JButton();
        removerSelecionadaButton = new javax.swing.JButton();
        filtrarButton = new javax.swing.JButton();

        dificuldadeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fácil", "Média", "Difícil" }));
        dificuldadeCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dificuldadeComboActionPerformed(evt);
            }
        });

        jLabel1.setText("Selecione a dificuldade da questão");

        dificuldadeCombo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fácil", "Média", "Difícil" }));
        dificuldadeCombo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dificuldadeCombo1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Selecione a dificuldade da questão");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        removerPanel.setBackground(new java.awt.Color(189, 231, 255));
        removerPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Colégio Poliedro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 12), new java.awt.Color(255, 149, 0))); // NOI18N

        materiaCombo.setBackground(new java.awt.Color(69, 172, 236));
        materiaCombo.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        materiaCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Português", "Literatura", "História", "Geografia", "Filosofia", "Sociologia", "Inglês", "Matemática", "Física", "Química", "Biologia" }));

        materiaLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        materiaLabel.setForeground(new java.awt.Color(255, 149, 0));
        materiaLabel.setText("Selecione a matéria");

        serieCombo.setBackground(new java.awt.Color(69, 172, 236));
        serieCombo.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        serieCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Primeiro", "Segundo", "Terceiro" }));
        serieCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serieComboActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 149, 0));
        jLabel2.setText("Selecione a série");

        dificuldadeCombo2.setBackground(new java.awt.Color(69, 172, 236));
        dificuldadeCombo2.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        dificuldadeCombo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fácil", "Média", "Difícil" }));
        dificuldadeCombo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dificuldadeCombo2ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 149, 0));
        jLabel4.setText("Selecione a dificuldade da questão");

        questoesTable.setBackground(new java.awt.Color(204, 224, 236));
        questoesTable.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        questoesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Enunciado", "Matéria"
            }
        ));
        jScrollPane1.setViewportView(questoesTable);

        voltarRemoverButton.setBackground(new java.awt.Color(69, 172, 236));
        voltarRemoverButton.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        voltarRemoverButton.setText("Voltar");
        voltarRemoverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarRemoverButtonActionPerformed(evt);
            }
        });

        removerSelecionadaButton.setBackground(new java.awt.Color(69, 172, 236));
        removerSelecionadaButton.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        removerSelecionadaButton.setText("Remover Selecionada");
        removerSelecionadaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerSelecionadaButtonActionPerformed(evt);
            }
        });

        filtrarButton.setBackground(new java.awt.Color(69, 172, 236));
        filtrarButton.setFont(new java.awt.Font("Trebuchet MS", 0, 12)); // NOI18N
        filtrarButton.setText("Filtrar");
        filtrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filtrarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout removerPanelLayout = new javax.swing.GroupLayout(removerPanel);
        removerPanel.setLayout(removerPanelLayout);
        removerPanelLayout.setHorizontalGroup(
            removerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(materiaCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(serieCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(removerPanelLayout.createSequentialGroup()
                .addGroup(removerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(materiaLabel)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(dificuldadeCombo2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(removerPanelLayout.createSequentialGroup()
                .addContainerGap(232, Short.MAX_VALUE)
                .addComponent(voltarRemoverButton)
                .addGap(130, 130, 130)
                .addComponent(removerSelecionadaButton)
                .addGap(127, 127, 127)
                .addComponent(filtrarButton)
                .addGap(228, 228, 228))
        );
        removerPanelLayout.setVerticalGroup(
            removerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(removerPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(materiaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(materiaCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(serieCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dificuldadeCombo2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(removerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(voltarRemoverButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filtrarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removerSelecionadaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(133, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(removerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(removerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dificuldadeComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dificuldadeComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dificuldadeComboActionPerformed

    private void dificuldadeCombo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dificuldadeCombo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dificuldadeCombo1ActionPerformed

    private void dificuldadeCombo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dificuldadeCombo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dificuldadeCombo2ActionPerformed

    private void filtrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filtrarButtonActionPerformed
        try {
            // TODO add your handling code here:
            carregarQuestoes();
        } catch (Exception ex) {
            Logger.getLogger(TelaRemoverQuestão.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_filtrarButtonActionPerformed

    private void removerSelecionadaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerSelecionadaButtonActionPerformed
        // TODO add your handling code here:
        int linha = questoesTable.getSelectedRow();
        if (linha != -1) {
            int id = (int) questoesTable.getValueAt(linha, 0);
            int confirm = JOptionPane.showConfirmDialog(this, "Remover essa questão?");
            if (confirm == JOptionPane.YES_OPTION) {
                boolean ok = false;
                try {
                    ok = new DAO().removerQuestaoPorId(id);
                } catch (Exception ex) {
                    Logger.getLogger(TelaRemoverQuestão.class.getName()).log(Level.SEVERE, null, ex);
                }
                if (ok) {
                JOptionPane.showMessageDialog(this, "Questão removida!");
                    try {
                        carregarQuestoes();
                    } catch (Exception ex) {
                        Logger.getLogger(TelaRemoverQuestão.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Erro ao remover.");
            }
        }
    } else {
        JOptionPane.showMessageDialog(this, "Selecione uma questão na tabela.");
    }
    }//GEN-LAST:event_removerSelecionadaButtonActionPerformed

    private void serieComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serieComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serieComboActionPerformed

    private void voltarRemoverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarRemoverButtonActionPerformed
        // TODO add your handling code here:
        TelaGerenciarQuestoes tela = new TelaGerenciarQuestoes();
        tela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_voltarRemoverButtonActionPerformed

    private void carregarQuestoes() throws Exception {
        String materia = materiaCombo.getSelectedItem().toString().trim();
        String serie = serieCombo.getSelectedItem().toString().trim();
        String dificuldade = dificuldadeCombo2.getSelectedItem().toString().trim();

        DefaultTableModel modelo = (DefaultTableModel) questoesTable.getModel();
        modelo.setRowCount(0);

        List<Questao> questoes = new DAO().buscarQuestoesPorFiltro(materia, serie, dificuldade);

        for (Questao q : questoes) {
         modelo.addRow(new Object[]{q.getId(), q.getEnunciado(), q.getCorreta()});
        }
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaRemoverQuestão.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaRemoverQuestão.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaRemoverQuestão.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaRemoverQuestão.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaRemoverQuestão().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> dificuldadeCombo;
    private javax.swing.JComboBox<String> dificuldadeCombo1;
    private javax.swing.JComboBox<String> dificuldadeCombo2;
    private javax.swing.JButton filtrarButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> materiaCombo;
    private javax.swing.JLabel materiaLabel;
    private javax.swing.JTable questoesTable;
    private javax.swing.JPanel removerPanel;
    private javax.swing.JButton removerSelecionadaButton;
    private javax.swing.JComboBox<String> serieCombo;
    private javax.swing.JButton voltarRemoverButton;
    // End of variables declaration//GEN-END:variables
}
